server:
  port: 8082
spring:
  application:
    name: monitor-eureka    # 项目名称尽量用小写
security:
  user:
    name: user
    password: user
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    hostname: discovery    # 指定该Eureka实例的主机名
  server:
    enable-self-preservation: false			# 设为false，关闭自我保护
    eviction-interval-timer-in-ms: 4000    # 清理间隔（单位毫秒，默认是60*1000）
  client:
    healthcheck:
          enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://user:user@${eureka.instance.hostname}:8082/eureka/,http://user:user@${eureka.instance.hostname}:8082/eureka/
#spring:
# devtools:
#    restart:
#      additional-paths: src/main/java
# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode
# 参考文档：http://my.oschina.net/buwei/blog/618756